name: CI/CD Workflow

env:
  GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
  
on:
  push:
    branches:
      - main

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
  build:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - run: npm install
      - run: npm run build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: build